### ISSUE TITLE
Can't build for Electron 31

### ISSUE THREAD

**Issue by johnlindquist** [akiflow/electron-panel-window#5]
Electron 31 was released today.
- https://releases.electronjs.org/release/v31.0.0
> Note: They made some internal changes to "IsPanel" and other methods which seems to impact related libraries, still investigating: 

https://github.com/electron/electron/compare/v31.0.0...v30.0.0#diff-148ef9a1a6f049d9fef8c6272a4871d89315f8fc6cd80dc2d41a28b21b29184c

 I attempted to upgrade, but re-building electron-panel-window caused these errors:

```bash
➜  testing-mac-panel-window-destroy npm run rebuild

> testing-mac-panel-window-destroy@1.0.0 rebuild
> electron-rebuild -f -w @akiflow/electron-panel-window

⠙ Building module: @akiflow/electron-panel-window, Completed: 0  CXX(target) Release/obj.target/NativeExtension/NativeExtension.o
In file included from ../NativeExtension.mm:1:
In file included from ../functions.h:4:
../../../nan/nan.h:208:12: error: no template named 'CopyablePersistentTraits' in namespace 'v8'; did you mean simply 'CopyablePersistentTraits'?
    public v8::CopyablePersistentTraits<T> {};
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
           CopyablePersistentTraits
../../../nan/nan.h:207:7: note: 'CopyablePersistentTraits' declared here
class CopyablePersistentTraits :
      ^
../../../nan/nan.h:208:12: error: circular inheritance between 'v8::CopyablePersistentTraits<T>' and 'CopyablePersistentTraits<T>'
    public v8::CopyablePersistentTraits<T> {};
           ^
../../../nan/nan.h:688:39: warning: 'IdleNotificationDeadline' is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
    return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
                                      ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8-isolate.h:1380:3: note: 'IdleNotificationDeadline' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8config.h:570:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../NativeExtension.mm:1:
In file included from ../functions.h:4:
../../../nan/nan.h:2642:15: warning: 'SetAccessor' is deprecated: Use SetNativeDataProperty instead [-Wdeprecated-declarations]
  return obj->SetAccessor(
              ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8-object.h:348:3: note: 'SetAccessor' has been explicitly marked deprecated here
  V8_DEPRECATED("Use SetNativeDataProperty instead")
  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8config.h:570:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../NativeExtension.mm:1:
In file included from ../functions.h:4:
../../../nan/nan.h:2718:19: warning: 'NamedPropertyHandlerConfiguration' is deprecated: Provide interceptor callbacks with new signatures instead (NamedPropertyXxxCallback) [-Wdeprecated-declarations]
  tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
                  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8-template.h:812:3: note: 'NamedPropertyHandlerConfiguration' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8config.h:570:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../NativeExtension.mm:1:
In file included from ../functions.h:4:
../../../nan/nan.h:2718:19: warning: 'NamedPropertyHandlerConfiguration' is deprecated: Provide interceptor callbacks with new signatures instead (NamedPropertyXxxCallback) [-Wdeprecated-declarations]
  tpl->SetHandler(v8::NamedPropertyHandlerConfiguration(
                  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8-template.h:812:3: note: 'NamedPropertyHandlerConfiguration' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8config.h:570:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../NativeExtension.mm:1:
In file included from ../functions.h:4:
In file included from ../../../nan/nan.h:2954:
../../../nan/nan_scriptorigin.h:19:7: warning: 'ScriptOrigin' is deprecated: Use constructor without the isolate. [-Wdeprecated-declarations]
      v8::ScriptOrigin(v8::Isolate::GetCurrent(), name) {}
      ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8-message.h:64:3: note: 'ScriptOrigin' has been explicitly marked deprecated here
  V8_DEPRECATED("Use constructor without the isolate.")
  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8config.h:570:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../NativeExtension.mm:1:
In file included from ../functions.h:4:
In file included from ../../../nan/nan.h:2954:
../../../nan/nan_scriptorigin.h:23:7: warning: 'ScriptOrigin' is deprecated: Use constructor without the isolate. [-Wdeprecated-declarations]
      v8::ScriptOrigin(v8::Isolate::GetCurrent()
      ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8-message.h:64:3: note: 'ScriptOrigin' has been explicitly marked deprecated here
  V8_DEPRECATED("Use constructor without the isolate.")
  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8config.h:570:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
In file included from ../NativeExtension.mm:1:
In file included from ../functions.h:4:
In file included from ../../../nan/nan.h:2954:
../../../nan/nan_scriptorigin.h:30:7: warning: 'ScriptOrigin' is deprecated: Use constructor without the isolate. [-Wdeprecated-declarations]
      v8::ScriptOrigin(v8::Isolate::GetCurrent()
      ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8-message.h:64:3: note: 'ScriptOrigin' has been explicitly marked deprecated here
  V8_DEPRECATED("Use constructor without the isolate.")
  ^
/Users/johnlindquist/.electron-gyp/31.0.0/include/node/v8config.h:570:35: note: expanded from macro 'V8_DEPRECATED'
# define V8_DEPRECATED(message) [[deprecated(message)]]
                                  ^
7 warnings and 2 errors generated.
make: *** [Release/obj.target/NativeExtension/NativeExtension.o] Error 1
Error: `make` failed with exit code: 2
    at ChildProcess.onExit (/Users/johnlindquist/dev/testing-mac-panel-window-destroy/node_modules/node-gyp/lib/build.js:203:23)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/johnlindquist/dev/testing-mac-panel-window-destroy/node_modules/@akiflow/electron-panel-window'

Error: node-gyp failed to rebuild '/Users/johnlindquist/dev/testing-mac-panel-window-destroy/node_modules/@akiflow/electron-panel-window'
    at ChildProcess.<anonymous> (/Users/johnlindquist/dev/testing-mac-panel-window-destroy/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
➜  testing-mac-panel-window-destroy
```

Any ideas?

**Comment by KarthikeyanKanniappan** [comment]
Yes, electron panel window is throwing the above error in 31x. Any suggestions

**Comment by oltreseba** [comment]
We release an update that build for electron 32.
It uses a new version of NAN which is not from the official repo though. Waiting for them to push update it.
